version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "7004:7004"
    environment:
      - NODE_ENV=production
    restart: unless-stopped